//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SHPUDEntities1 : DbContext
    {
        public SHPUDEntities1()
            : base("name=SHPUDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_DISEASE> TBL_DISEASE { get; set; }
        public virtual DbSet<TBL_DISEASE_DETAILS> TBL_DISEASE_DETAILS { get; set; }
        public virtual DbSet<TBL_DOCTOR> TBL_DOCTOR { get; set; }
        public virtual DbSet<TBL_HOSPITAL> TBL_HOSPITAL { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<TBL_USER_HEALTH_RECORD> TBL_USER_HEALTH_RECORD { get; set; }
        public virtual DbSet<TBL_DOCTOR_DETAILS> TBL_DOCTOR_DETAILS { get; set; }
        public virtual DbSet<TBL_HOSPITAL_DETAILS> TBL_HOSPITAL_DETAILS { get; set; }
        public virtual DbSet<CONTACT_EMAILS> CONTACT_EMAILS { get; set; }
        public virtual DbSet<TBL_BOOKMARK> TBL_BOOKMARK { get; set; }
        public virtual DbSet<TBL_BOOKING> TBL_BOOKING { get; set; }
    
        public virtual int P_SET_USER(string p_NAME, string p_ADDRESS, string p_PASSWORD, string p_EMAIL, string p_GENDER, Nullable<System.DateTime> p_DOB, string p_CONTACT, string p_IMAGE, ObjectParameter v_OUT)
        {
            var p_NAMEParameter = p_NAME != null ?
                new ObjectParameter("P_NAME", p_NAME) :
                new ObjectParameter("P_NAME", typeof(string));
    
            var p_ADDRESSParameter = p_ADDRESS != null ?
                new ObjectParameter("P_ADDRESS", p_ADDRESS) :
                new ObjectParameter("P_ADDRESS", typeof(string));
    
            var p_PASSWORDParameter = p_PASSWORD != null ?
                new ObjectParameter("P_PASSWORD", p_PASSWORD) :
                new ObjectParameter("P_PASSWORD", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_GENDERParameter = p_GENDER != null ?
                new ObjectParameter("P_GENDER", p_GENDER) :
                new ObjectParameter("P_GENDER", typeof(string));
    
            var p_DOBParameter = p_DOB.HasValue ?
                new ObjectParameter("P_DOB", p_DOB) :
                new ObjectParameter("P_DOB", typeof(System.DateTime));
    
            var p_CONTACTParameter = p_CONTACT != null ?
                new ObjectParameter("P_CONTACT", p_CONTACT) :
                new ObjectParameter("P_CONTACT", typeof(string));
    
            var p_IMAGEParameter = p_IMAGE != null ?
                new ObjectParameter("P_IMAGE", p_IMAGE) :
                new ObjectParameter("P_IMAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_SET_USER", p_NAMEParameter, p_ADDRESSParameter, p_PASSWORDParameter, p_EMAILParameter, p_GENDERParameter, p_DOBParameter, p_CONTACTParameter, p_IMAGEParameter, v_OUT);
        }
    }
}
