//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_HEALTH_RECORD
    {
        public int RECORD_ID { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string PREVIOUS_DISEASE { get; set; }
        public Nullable<int> DOCTOR_ID { get; set; }
        public string DATE_OF_CHECKUP { get; set; }
        public string IMAGE { get; set; }
    }
}
