//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BOOKING
    {
        public Nullable<int> Doctor_ID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Message { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Remarks { get; set; }
        public int ID { get; set; }
    }
}
