//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HOSPITAL
    {
        public int HOSPITAL_ID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string HOSPITAL_NAME { get; set; }
        public string HOSPITAL_ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string SPECIALIZATION { get; set; }
        public string HOSPITAL_IMAGE { get; set; }
        public string CONTACT { get; set; }
    }
}
