//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DISEASE_DETAILS
    {
        public int DISEASE_ID { get; set; }
        public string DISEASE_DESCRIPTION { get; set; }
        public string TREATMENT { get; set; }
        public string SUGGESTION { get; set; }
        public string IMAGE { get; set; }
        public int DETAIL_ID { get; set; }
    }
}
