//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADMIN
    {
        public int ADMIN_ID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string ADMIN_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string ADMIN_IMAGE { get; set; }
        public string WORK_HOSPITAL { get; set; }
        public string GENDER { get; set; }
        public string PASSWORD { get; set; }
        public string CONTACT { get; set; }
    }
}
