//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HOSPITAL_DETAILS
    {
        public int HOSPITAL_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string MORE_INFO { get; set; }
        public string REMARKS { get; set; }
        public int DETAIL_ID { get; set; }
    }
}
