//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHPUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DOCTOR_DETAILS
    {
        public int DETAIL_ID { get; set; }
        public int DOCTOR_ID { get; set; }
        public string DOCTOR_DESCRIPTION { get; set; }
        public string DOCTOR_EDUCATION { get; set; }
        public string DOCTOR_SPECIALIZATION_DETAILS { get; set; }
    }
}
